apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-{{ .Chart.Name }}
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-uploads-{{ .Chart.Name }}
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi

