apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: do-backup-secret
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  parameters:
    objects: |
      - objectName: "access_key"
        secretPath: "secret/data/backup-secret"
        secretKey: "access_key"
      - objectName: "secret_key"
        secretPath: "secret/data/backup-secret"
        secretKey: "secret_key"
    roleName: csi
    vaultAddress: https://vault.default:8200
    vaultSkipTLSVerify: "true"
  provider: vault
  secretObjects:
  - data:
    - key: access_key
      objectName: access_key
    - key: secret_key
      objectName: secret_key
    secretName: do-backup-secret
    type: Opaque
