{{- $Plugins := .Values.plugins | splitList "," -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hostkraken.domainDashed" . }}-configmap
  namespace: {{ include "hostkraken.domainDashed" . }}
data:
  00_pgsql.conf: |
    extension=pgsql
  db-config.php: |-
    <?php
    /**
    * Use HyperDB to just use the replica for frontend reads.
    * Register the primary server to HyperDB
    */
    $wpdb->add_database( array(
            'host'     => "mysql-galera-mariadb-galera-0.mysql-galera-mariadb-galera-headless.mysql",
            'user'     => "DB_USER",
            'password' => "DB_PASSWORD",
            'name'     => "DB_NAME",
            'write'    => 1, 
            'read'     => 1,
    ));
    /**
    * Register replica database server if it's available in this environment
    */
            $wpdb->add_database(array(
                    'host'     => "mysql-galera-mariadb-galera-1.mysql-galera-mariadb-galera-headless.mysql",
                    'user'     => "DB_USER",
                    'password' => "DB_PASSWORD",
                    'name'     => "DB_NAME",
                    'write'    => 1, 
                    'read'     => 1, 
            ));
            
            $wpdb->add_database(array(
                    'host'     => "mysql-galera-mariadb-galera-2.mysql-galera-mariadb-galera-headless.mysql",
                    'user'     => "DB_USER",
                    'password' => "DB_PASSWORD",
                    'name'     => "DB_NAME",
                    'write'    => 1, 
                    'read'     => 1, 
          
  disable-updates.php: |
    // hide update notifications
    function remove_core_updates(){

    global $wp_version;return(object) array('last_checked'=> time(),'version_checked'=> $wp_version,);
     }
    add_filter('pre_site_transient_update_core','remove_core_updates'); //hide updates for WordPress itself
    add_filter('pre_site_transient_update_plugins','remove_core_updates'); //hide updates for all plugins
    add_filter('pre_site_transient_update_themes','remove_core_updates'); //hide updates for all themes
    function remove_admin_menu_items() {
    $remove_menu_items = array(__('Dashboard'));
    global $menu;
    end ($menu);
    while (prev($menu)){
        $item = explode(' ',$menu[key($menu)][0]);
    if(in_array($item[0] != NULL?$item[0]:"" , $remove_menu_items)){
    unset($menu[key($menu)]);}
    }
    } 
    add_action('admin_menu', 'remove_admin_menu_items');
    function remove_plugin_install() {
    $page = remove_submenu_page( 'plugins.php', 'plugin-install.php' );
    $page = remove_submenu_page( 'themes.php', 'theme-editor.php' );
    $page = remove_submenu_page( 'themes.php', 'themes.php' );
    $page = remove_submenu_page( 'tools.php', 'site-health.php' );
    $page = remove_submenu_page( 'tools.php', 'import.php' );
    $page = remove_submenu_page( 'tools.php', 'export.php' );
    $page = remove_submenu_page( 'plugins.php', 'plugin-editor.php' );
    // $page[0] is the menu title
    // $page[1] is the minimum level or capability required
    // $page[2] is the URL to the item's file
    }
    add_action( 'admin_menu', 'remove_plugin_install', 999 );



  database-migration.sh: |
    set -x
    rm -f /usr/html/wp-admin/install.php; 
    cp /configs/wp-config.php /usr/html;
    chown nginx: /usr/html/wp-config.php;
    wget https://downloads.wordpress.org/plugin/hyperdb.1.8.zip;
    unzip hyperdb.1.8.zip;
    mv hyperdb/db.php /usr/html/wp-content;
    sleep 1;
    cp /configs/db-config.php /usr/html;
    # gross hacks for old sites
    case $DATABASE_NAME in
      *"db_"*)
        echo "Database name matches formmat. Continuing.."
        ;;
      *)
        echo "Database name does not match format. Fixing..."  
        dbtemp1=`echo $DATABASE_NAME`
        dbtemp=db_${dbtemp1}
        export DATABASE_NAME=$dbtemp
        ;;
    esac           
    case $DATABASE_USER in
      *"user_"*)
        echo "Database name matches format. Continuing.."
        ;;
      *)
        echo "Database user does not match format. Fixing..."  
        usertemp1=`echo $DATABASE_USER|head -c25`
        usertemp=user_${usertemp1}
        export DATABASE_USER=$usertemp
        ;;
    esac
    sed -i "s/DB_USER/$DATABASE_USER/g" /usr/html/db-config.php;
    sed -i "s/DB_PASSWORD/$DATABASE_PASS/g" /usr/html/db-config.php;
    sed -i "s/DB_NAME/$DATABASE_NAME/g" /usr/html/db-config.php;
    sed -i "s/ADATABASE_USER/$DATABASE_USER/g" /usr/html/wp-config.php;
    sed -i "s/ADATABASE_PASS/$DATABASE_PASS/g" /usr/html/wp-config.php;
    sed -i "s/ADATABASE_NAME/$DATABASE_NAME/g" /usr/html/wp-config.php;
    if ! /usr/bin/wp-cli core is-installed --path='/usr/html'; then
    /usr/bin/wp-cli core install --path='/usr/html' --url="`echo {{ .Release.Name }} | tr '-' '.' `" --title='{{ .Values.site_title | default "New Deployment" }}' --admin_user='admin' --admin_email='roger@hostkraken.com' --admin_password='H0stKr4ken' || true
    /usr/bin/wp-cli plugin deactivate hello --path=/usr/html
    /usr/bin/wp-cli plugin uninstall hello --path=/usr/html
    fi
    {{- range $Plugins }}
    if ! /usr/bin/wp-cli plugin is-installed {{ . }} --path='/usr/html' ; then
    /usr/bin/wp-cli plugin install {{ . }} --path=/usr/html || true    
    fi
    if ! /usr/bin/wp-cli plugin is-active {{ . }} --path='/usr/html' ; then
    /usr/bin/wp-cli plugin activate {{ . }} --path=/usr/html || true
    fi
    {{- end }}
    /usr/bin/wp-cli theme install --path='/usr/html' "https://krakenwpassets.s3.us-west-1.amazonaws.com/Divi.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECAaCXVzLXdlc3QtMSJHMEUCIQDTflWhLJMtCmwLvwTyJqxx17i8D7CLL2KBd76Q0kb5WQIgY9mU%2FwXcxxMJUiZFbt16iwemduD5RPEk9wZNXDdDUqEq7QIIqf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw0NTIzOTQ0MzQ1ODYiDANYmopnIvrbl4L72CrBAgKHJn%2BRXKFMEHfJjckNfxCEVS4UYTgfNYegNO6vQDIYuCoLPuHJPYzR6qrMXbrjEhyb9DNeO4%2BgUz%2Fl9S0yS0wOcRPFB2rCR%2FrF1SJTXMddQEsdiESsh4lVfQj0lZfUv6OooRVjaCx%2F3fXC%2FthKuYV9TvXt3n9kTcM18246jkwoYYOl3CAurNFMfQyvQHjycPIh7PCCJLj7PW1M077Bgwb5UYsa0QsR0cp8TfZ7uMAyJv%2B%2F4KI2v1II2XjpUsH8MeE4hjdC9MZN2uRcMg1ODZKo3ppeQaIsb6AcTJwT8%2Bay7jsqhuuNOA1zt9kpp6aWdZP7kbfjVtID71h3JF1h737zEvEY0Z1ooWIDVpHtLYEa4qX9FKUf%2FNvWrmHWUf%2Fez%2FcrXHT3DFeh8i7YlfLWxPBtZYG3dkb3j5c%2Bvm0svuhpHzDIk4KSBjqzAkp%2FUdoz980T%2BrRqNZUBHwdMq%2BwmgoOCk3dJcToR8Pm2c3p%2FQlHDWByCW%2BbzhHmUH%2Bfn5Zrsm8CfgutwXTYIDoOiwmKibVvoJe0OeKpsqlR1avrc%2FKkBL1W%2FVDTXPGUvjAjNQSU8nJJPeA2KmZ2FAkM3L6qS7zJBx5WZcVDaIRCSMzjb6X84114gdrcr2K7zLkWS9828feBTrOwzGTndhtabap7T05Zl4AQIRQFk4hm1jcAYGXmdQNIbWtOzWHdlOgUDFGdeOMomxJLmpmg0wpI0hckOiouNCqC7l25sFCrKse0mYfKJz0SMiYBLFlT7r3hRftJ%2F3TbeER0K8ykqwtYC%2BYnjiVqrhwTYH49frItw6UDWu6dCeMwUVfHdsJL%2F1CfgMoCIxbNsjam7hKRSPooV5WI%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220327T161625Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIAWSVGPIANFPOHRH47%2F20220327%2Fus-west-1%2Fs3%2Faws4_request&X-Amz-Signature=bd6422c88b3a4560894b347e25b7bbea7fe0e089e36a0e72405a4f14b90a59cc"
    /usr/bin/wp-cli theme install --activate {{ .Values.wp_theme|default "twentytwenty" }} --path='/usr/html'
    /usr/bin/wp-cli theme activate {{ .Values.wp_theme|default "twentytwenty" }} --path='/usr/html'
    export disabledupdates=`grep -c "hide update" /usr/html/wp-content/themes/{{ .Values.wp_theme|default "twentytwenty" }}/functions.php`
    if [[ "$disabledupdates" -eq 0 ]]; then
      cat /configs/disable-updates.php >>/usr/html/wp-content/themes/{{ .Values.wp_theme|default "twentytwenty" }}/functions.php
    fi
    rm -f /usr/html/wp-admin/plugin-editor.php
    rm -f /usr/html/wp-admin/plugin-install.php
    rm -f /usr/html/wp-admin/site-health.php
    rm -f /usr/html/wp-admin/site-health-info.php
    rm -f /usr/html/wp-admin/import.php
    rm -f /usr/html/wp-admin/theme-editor.php
    rm -f /usr/html/wp-admin/export.php
    sed -i 's/<a.*plugin-install.php.*\/a>//g' /usr/html/wp-admin/plugins.php

  wp-config.php: |
    <?php 
    /* MySQL settings */
    define( 'DB_NAME',     'ADATABASE_NAME' );
    define( 'DB_USER',     'ADATABASE_USER' );
    define( 'DB_PASSWORD', 'ADATABASE_PASS' );
    define( 'DB_HOST',     'mysql-primary.mysql' );
    define( 'DB_CHARSET',  'utf8' );
    #define('FORCE_SSL_ADMIN', true);
    define('SITE_URL', "https://{{ .Values.site_url }}");
    /* MySQL database table prefix. */
    $table_prefix = '{{- .Values.table_prefix | default "wp_" -}}';
    //Begin Really Simple SSL Load balancing fix
    if ((isset($_ENV["HTTPS"]) && ("on" == $_ENV["HTTPS"]))
    || (isset($_SERVER["HTTP_X_FORWARDED_SSL"]) && (strpos($_SERVER["HTTP_X_FORWARDED_SSL"], "1") !== false))
    || (isset($_SERVER["HTTP_X_FORWARDED_SSL"]) && (strpos($_SERVER["HTTP_X_FORWARDED_SSL"], "on") !== false))
    || (isset($_SERVER["HTTP_CF_VISITOR"]) && (strpos($_SERVER["HTTP_CF_VISITOR"], "https") !== false))
    || (isset($_SERVER["HTTP_CLOUDFRONT_FORWARDED_PROTO"]) && (strpos($_SERVER["HTTP_CLOUDFRONT_FORWARDED_PROTO"], "https") !== false))
    || (isset($_SERVER["HTTP_X_FORWARDED_PROTO"]) && (strpos($_SERVER["HTTP_X_FORWARDED_PROTO"], "https") !== false))
    || (isset($_SERVER["HTTP_X_PROTO"]) && (strpos($_SERVER["HTTP_X_PROTO"], "SSL") !== false))
    ) {
      $_SERVER["HTTPS"] = "on";
    }
    //END Really Simple SSL 

    /* Authentication Unique Keys and Salts. */
    /* https://api.wordpress.org/secret-key/1.1/salt/ */
    define( 'AUTH_KEY',         '{{ randAlphaNum 16 }}' );
    define( 'SECURE_AUTH_KEY',  '{{ randAlphaNum 16 }}' );
    define( 'LOGGED_IN_KEY',    '{{ randAlphaNum 16 }}' );
    define( 'NONCE_KEY',        '{{ randAlphaNum 16 }}' );
    define( 'AUTH_SALT',        '{{ randAlphaNum 16 }}' );
    define( 'SECURE_AUTH_SALT', '{{ randAlphaNum 16 }}' );
    define( 'LOGGED_IN_SALT',   '{{ randAlphaNum 16 }}' );
    define( 'NONCE_SALT',       '{{ randAlphaNum 16 }}' );


    /* Absolute path to the WordPress directory. */
    if ( !defined('ABSPATH') )
      define('ABSPATH', dirname(__FILE__) . '/');

    /* Sets up WordPress vars and included files. */
    require_once(ABSPATH . 'wp-settings.php');
