apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-{{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
  annotations: {}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 13 }}
        {{- end }}
          serviceAccountName: {{ include "hostkraken.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 13 }}
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "hostkraken.domainDashed" . }}-configmap
            - name: wp-uploads-{{ include "hostkraken.domainDashed" . }}
              persistentVolumeClaim:
                claimName: wp-uploads-{{ include "hostkraken.domainDashed" . }}
            - name: s3-creds
              csi:
                driver: "secrets-store.csi.k8s.io"
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "vault-s3-{{ include "hostkraken.domainDashed" . }}"         
            - name: dummy-do-secret
              csi:
                driver: "secrets-store.csi.k8s.io"
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "do-backup-secret"                            
          containers:
            - name: {{ include "hostkraken.domainDashed" . }}-dailybackup
              env:
                - name: DATABASE_HOST
                  value: "{{ include "hostkraken.domainDashed" . }}-mysql.{{ include "hostkraken.domainDashed" . }}.svc"
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef: 
                      name: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
                      key: user
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
                      key: name
                - name: DATABASE_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
                      key: pass
                - name: BUCKET
                  value: "hostkraken-backup"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom: 
                    secretKeyRef:
                      name: {{ include "hostkraken.domainDashed" . }}-s3-creds-secret
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "hostkraken.domainDashed" . }}-s3-creds-secret
                      key: AWS_SECRET_ACCESS_KEY
                - name: SITE_NAME
                  value: {{ .Values.domain }}
              volumeMounts:
              - name: "dummy-do-secret"
                mountPath: "/mnt/dookie"
                readOnly: true
              - name: "s3-creds"
                mountPath: "/mnt/secrets-store"
                readOnly: true              
              - name: config-volume
                mountPath: /configs
              - name: wp-uploads-{{ include "hostkraken.domainDashed" . }}
                mountPath: /usr/html/wp-content/uploads
              securityContext:
                {{- toYaml .Values.securityContext | nindent 17 }}
              image: "registry.hostkraken.com/dailybackup:argo"
              imagePullPolicy: Always
              args:
              - /bin/backup-site {{ include "hostkraken.domainDashed" . }}
