apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-REPLACE
  annotations:
    vault.banzaicloud.io/vault-addr: "https://vaultino.vault-infra.svc:8200"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
