apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "hostkraken.domainDashed" . }}
  name: restore-cleanup
rules:
- apiGroups: ["hostkraken.com"] # "" indicates the core API group
  resources: ["restorejobs"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: restore-cleanup
  namespace: {{ include "hostkraken.domainDashed" . }}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: default # "name" is case sensitive
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: restore-cleanup # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io