{{- $Plugins := .Values.plugins | splitList "," -}}
{{- $PluginsCount := len $Plugins -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
  labels:
    {{- include "hostkraken.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hostkraken.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: 
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "hostkraken.selectorLabels" . | nindent 8 }}
        approle: web
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: default
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: db-creds
          csi:
            driver: "secrets-store.csi.k8s.io"
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-db-{{ include "hostkraken.domainDashed" . }}"
        - name: config-volume
          configMap:
            name: {{ include "hostkraken.domainDashed" . }}-configmap
        - name: wp-uploads-{{ include "hostkraken.domainDashed" . }}
          persistentVolumeClaim:
            claimName: wp-uploads-{{ include "hostkraken.domainDashed" . }}
        - name: wp-root-{{ include "hostkraken.domainDashed" . }}
          persistentVolumeClaim:
            claimName: wp-root-{{ include "hostkraken.domainDashed" . }}
      containers:
        - name: {{ include "hostkraken.domainDashed" . }}
          volumeMounts:
          - name: "db-creds"
            mountPath: "/mnt/secrets-store"
            readOnly: true
          - name: config-volume
            mountPath: /configs
          - name: wp-root-{{ include "hostkraken.domainDashed" . }}
            mountPath: /usr/html
          - name: wp-uploads-{{ include "hostkraken.domainDashed" . }}
            mountPath: /usr/html/wp-content/uploads
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "registry.hostkraken.com/{{ .Values.domain }}:latest"
          imagePullPolicy: Always
          env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
                key: user
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
                key: pass
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
                key: name
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command: 
              - pgrep
              - nginx
            initialDelaySeconds: {{ add ( mul $PluginsCount 10 ) 90 }}
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command: 
              - pgrep
              - nginx
            initialDelaySeconds: {{ add ( mul $PluginsCount 10 ) 90 }}
            periodSeconds: 5
            failureThreshold: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
