apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret-{{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: create-secret-{{ include "hostkraken.domainDashed" . }}
    spec:
      volumes:
        - name: register-secret
          csi:
            driver: "secrets-store.csi.k8s.io"
            readOnly: true
            volumeAttributes:
              secretProviderClass: "register-secret"
      containers:
      - command:
        - /bin/sh
        args:
        - /create-secret-containerized.sh 
        volumeMounts:
          - name: "register-secret"
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
        - name: VAULT_ADDR
          value: https://vault-0.default.svc:8200
        - name: SITENAME
          value: {{ .Values.domain }}
        - name: CLOUDFLARE_EMAIL
          valueFrom:
              secretKeyRef:
                name: register-secret
                key: cf_email
        - name: CLOUDFLARE_API_KEY
          valueFrom:
              secretKeyRef:
                name: register-secret
                key: cf_key
        - name: CF_ACCOUNT_ID
          valueFrom:
              secretKeyRef:
                name: register-secret
                key: cf_account
        - name: NAMESILO_KEY
          valueFrom:
              secretKeyRef:
                name: register-secret
                key: ns_key
        image: registry.hostkraken.com/secret-maker:0.1
        imagePullPolicy: Always
        name: secret-maker
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-business-business
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: secret-creator
      serviceAccountName: secret-creator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-repo-{{ include "hostkraken.domainDashed" . }}
  namespace: argocd-workflows
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: create-repo-{{ include "hostkraken.domainDashed" . }}
    spec:
      containers:
      - command: ["/bin/sh","-c"]
        args:
        - echo $GITHUB_TOKEN | gh auth login --with-token ; echo 'y' | gh repo create HostKraken/{{ .Values.domain }} --private -p kraken-site-template 
        env:
        - name: GITHUB_TOKEN
          valueFrom:
              secretKeyRef:
                name: github-maker
                key: token
        - name: SITENAME
          value: "{{ .Values.domain }}"
        image: rossbannerman/gh:latest
        imagePullPolicy: Always
        name: repo-maker
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-business-business
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}