apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: {{ include "hostkraken.domainDashed" . }}
  namespace: rook-ceph
spec:
  dataPool:
    compressionMode: none
    erasureCoded:
      codingChunks: 1
      dataChunks: 2
    failureDomain: host
    mirroring: {}
    quotas: {}
    replicated:
      size: 0
    statusCheck:
      mirror: {}
  gateway:
    instances: 1
    placement: {}
    port: 80
    resources: {}
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
  metadataPool:
    compressionMode: none
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: host
    mirroring: {}
    quotas: {}
    replicated:
      size: 3
    statusCheck:
      mirror: {}
  preservePoolsOnDelete: true
  zone:
    name: ""