apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-{{ .Chart.Name }}
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-uploads-{{ .Chart.Name }}
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
