apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-uploads-{{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
      

