---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-REPLACE
spec:
  # Vault CSI Provider
  provider: vault
  secretObjects:
  - secretName: REPLACE-db-creds-secret
    type: Opaque
    data: 
    - objectName: db_user
      key: user
    - objectName: db_pass
      key: pass
    - objectName: db_rootpw
      key: rootpw
    - objectName: db_name
      key: name
  parameters:
    # Vault role name to use during login
    roleName: "csi"
    # Vault's hostname
    vaultAddress: "https://vault.default:8200"
    vaultSkipTLSVerify: "true"
    # TLS CA certification for validation
    objects: |
      - objectName: "db_name"
        secretPath: "secret/data/mysql/REPLACE"
        secretKey: "name"
      - objectName: "db_user"
        secretPath: "secret/data/mysql/REPLACE"
        secretKey: "user"
      - objectName: "db_pass"
        secretPath: "secret/data/mysql/REPLACE"
        secretKey: "pass"
      - objectName: "db_rootpw"
        secretPath: "secret/data/mysql/REPLACE"
        secretKey: "rootpw"
    # "objectName" is an alias used within the SecretProviderClass to reference 
    # that specific secret. This will also be the filename containing the secret.
    # "secretPath" is the path in Vault where the secret should be retrieved.
    # "secretKey" is the key within the Vault secret response to extract a value from.
