---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-{{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  # Vault CSI Provider
  provider: vault
  secretObjects:
  - secretName: {{ include "hostkraken.domainDashed" . }}-db-creds-secret
    type: Opaque
    data: 
    - objectName: db_user
      key: user
    - objectName: db_pass
      key: pass
    - objectName: db_rootpw
      key: rootpw
    - objectName: db_name
      key: name
  parameters:
    # Vault role name to use during login
    roleName: "csi"
    # Vault's hostname
    vaultAddress: "https://vault.default:8200"
    vaultSkipTLSVerify: "true"
    # TLS CA certification for validation
    objects: |
      - objectName: "db_name"
        secretPath: "secret/data/mysql/{{ include "hostkraken.domainDashed" . }}"
        secretKey: "name"
      - objectName: "db_user"
        secretPath: "secret/data/mysql/{{ include "hostkraken.domainDashed" . }}"
        secretKey: "user"
      - objectName: "db_pass"
        secretPath: "secret/data/mysql/{{ include "hostkraken.domainDashed" . }}"
        secretKey: "pass"
      - objectName: "db_rootpw"
        secretPath: "secret/data/mysql/{{ include "hostkraken.domainDashed" . }}"
        secretKey: "rootpw"
    # "objectName" is an alias used within the SecretProviderClass to reference 
    # that specific secret. This will also be the filename containing the secret.
    # "secretPath" is the path in Vault where the secret should be retrieved.
    # "secretKey" is the key within the Vault secret response to extract a value from.
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-s3-{{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  # Vault CSI Provider
  provider: vault
  secretObjects:
  - secretName: {{ include "hostkraken.domainDashed" . }}-s3-creds-secret
    type: Opaque
    data: 
    - objectName: AWS_ACCESS_KEY_ID
      key: AWS_ACCESS_KEY_ID
    - objectName: AWS_SECRET_ACCESS_KEY
      key: AWS_SECRET_ACCESS_KEY
  parameters:
    # Vault role name to use during login
    roleName: "csi"
    # Vault's hostname
    vaultAddress: "https://vault.default:8200"
    vaultSkipTLSVerify: "true"
    # TLS CA certification for validation
    objects: |
      - objectName: "AWS_ACCESS_KEY_ID"
        secretPath: "secret/data/backup-secret"
        secretKey: "access_key"
      - objectName: "AWS_SECRET_ACCESS_KEY"
        secretPath: "secret/data/backup-secret"
        secretKey: "secret_key"

    # "objectName" is an alias used within the SecretProviderClass to reference 
    # that specific secret. This will also be the filename containing the secret.
    # "secretPath" is the path in Vault where the secret should be retrieved.
    # "secretKey" is the key within the Vault secret response to extract a value from.
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: register-secret
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  # Vault CSI Provider
  provider: vault
  secretObjects:
  - secretName: register-secret
    type: Opaque
    data: 
    - objectName: cf_key
      key: cf_key
    - objectName: cf_account
      key: cf_account
    - objectName: cf_email
      key: cf_email
    - objectName: ns_key
      key: ns_key      
  parameters:
    # Vault role name to use during login
    roleName: "secret-creator"
    # Vault's hostname
    vaultAddress: "https://vault.default:8200"
    vaultSkipTLSVerify: "true"
    # TLS CA certification for validation
    objects: |
      - objectName: "cf_key"
        secretPath: "secret/data/registration"
        secretKey: "cf_key"
      - objectName: "cf_account"
        secretPath: "secret/data/registration"
        secretKey: "cf_account"
      - objectName: "cf_email"
        secretPath: "secret/data/registration"
        secretKey: "cf_email"
      - objectName: "ns_key"
        secretPath: "secret/data/registration"
        secretKey: "ns_key"        

    # "objectName" is an alias used within the SecretProviderClass to reference 
    # that specific secret. This will also be the filename containing the secret.
    # "secretPath" is the path in Vault where the secret should be retrieved.
    # "secretKey" is the key within the Vault secret response to extract a value from.    
