apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: {{ include "hostkraken.domainDashed" . }}
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: imgbuild-
                namespace: argocd-workflows
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: build-trigger           # We reference our first "template" here
                workflowTemplateRef: 
                  name: buildkit
                  clusterScope: true
                  