apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-{{ include "hostkraken.domainDashed" . }}
  namespace: argocd-workflows
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: {{ include "hostkraken.domainDashed" . }}
      eventName: {{ include "hostkraken.domainDashed" . }}
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          metadata:
            generateName: pipeline-{{ include "hostkraken.domainDashed" . }}-
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pipeline-{{ include "hostkraken.domainDashed" . }}
              spec:
                arguments:
                  parameters:
                    - name: domain
                      value: {{ .Values.domain }}
                    - name: domain-dashed
                      value: {{ include "hostkraken.domainDashed" . }}                    
                serviceAccountName: operate-workflow-sa
                entrypoint: pipeline          # We reference our first "template" here
                workflowTemplateRef: 
                  name: pipeline-build
 