apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  generateName: webhook-{{ include "hostkraken.domainDashed" . }}
  namespace: argocd-workflows
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: {{ include "hostkraken.domainDashed" . }}
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          metadata:
            generateName: imgbuild-{{ include "hostkraken.domainDashed" . }}-
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: imgbuild
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: build-trigger           # We reference our first "template" here
                workflowTemplateRef: 
                  name: buildkit
                  clusterScope: true
                  