apiVersion: v1
kind: Service
metadata:
  name: {{ include "hostkraken.domainDashed" . }}
  namespace: {{ include "hostkraken.domainDashed" . }}
  labels:
    {{- include "hostkraken.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hostkraken.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hostkraken.domainDashed" . }}-mysql
  labels:
    {{- include "hostkraken.labels_mysql" . | nindent 4 }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "hostkraken.selectorLabels_mysql" . | nindent 4 }}

