apiVersion: v1
kind: Service
metadata:
  name: {{ include "REPLACE.fullname" . }}
  labels:
    {{- include "REPLACE.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "REPLACE.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "REPLACE.fullname" . }}-mysql
  labels:
    {{- include "REPLACE.labels_mysql" . | nindent 4 }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "REPLACE.selectorLabels_mysql" . | nindent 4 }}

