apiVersion: crds.kubeflare.io/v1alpha1
kind: Zone
metadata:
  name: {{ .Values.domain }}
  namespace: {{ include "hostkraken.domainDashed" . }}
spec:
  apiToken: kubeflare-token
  settings:
    alwaysUseHttps: true
    alwaysOnline: true
    minify:
      css: true