apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: GARBAGE
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      secretName: tls-cert
  rules:
    - host: 
      http:
        paths:
          - path: "/"
            backend:
              serviceName: wordpress
              servicePort: 80
        {{- end }}
  {{- end }}
{{- end }}
